<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
<meta name="generator" content="pdoc 0.9.2" />
<title>raffiot.result API documentation</title>
<meta name="description" content="Data structure to represent the result of computation." />
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/sanitize.min.css" integrity="sha256-PK9q560IAAa6WVRRh76LtCaI8pjTJ2z11v0miyNNjrs=" crossorigin>
<link rel="preload stylesheet" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/11.0.1/typography.min.css" integrity="sha256-7l/o7C8jubJiy74VsKTidCy1yBkRtiUGbVkYBylBqUg=" crossorigin>
<link rel="stylesheet preload" as="style" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/github.min.css" crossorigin>
<style>:root{--highlight-color:#fe9}.flex{display:flex !important}body{line-height:1.5em}#content{padding:20px}#sidebar{padding:30px;overflow:hidden}#sidebar > *:last-child{margin-bottom:2cm}.http-server-breadcrumbs{font-size:130%;margin:0 0 15px 0}#footer{font-size:.75em;padding:5px 30px;border-top:1px solid #ddd;text-align:right}#footer p{margin:0 0 0 1em;display:inline-block}#footer p:last-child{margin-right:30px}h1,h2,h3,h4,h5{font-weight:300}h1{font-size:2.5em;line-height:1.1em}h2{font-size:1.75em;margin:1em 0 .50em 0}h3{font-size:1.4em;margin:25px 0 10px 0}h4{margin:0;font-size:105%}h1:target,h2:target,h3:target,h4:target,h5:target,h6:target{background:var(--highlight-color);padding:.2em 0}a{color:#058;text-decoration:none;transition:color .3s ease-in-out}a:hover{color:#e82}.title code{font-weight:bold}h2[id^="header-"]{margin-top:2em}.ident{color:#900}pre code{background:#f8f8f8;font-size:.8em;line-height:1.4em}code{background:#f2f2f1;padding:1px 4px;overflow-wrap:break-word}h1 code{background:transparent}pre{background:#f8f8f8;border:0;border-top:1px solid #ccc;border-bottom:1px solid #ccc;margin:1em 0;padding:1ex}#http-server-module-list{display:flex;flex-flow:column}#http-server-module-list div{display:flex}#http-server-module-list dt{min-width:10%}#http-server-module-list p{margin-top:0}.toc ul,#index{list-style-type:none;margin:0;padding:0}#index code{background:transparent}#index h3{border-bottom:1px solid #ddd}#index ul{padding:0}#index h4{margin-top:.6em;font-weight:bold}@media (min-width:200ex){#index .two-column{column-count:2}}@media (min-width:300ex){#index .two-column{column-count:3}}dl{margin-bottom:2em}dl dl:last-child{margin-bottom:4em}dd{margin:0 0 1em 3em}#header-classes + dl > dd{margin-bottom:3em}dd dd{margin-left:2em}dd p{margin:10px 0}.name{background:#eee;font-weight:bold;font-size:.85em;padding:5px 10px;display:inline-block;min-width:40%}.name:hover{background:#e0e0e0}dt:target .name{background:var(--highlight-color)}.name > span:first-child{white-space:nowrap}.name.class > span:nth-child(2){margin-left:.4em}.inherited{color:#999;border-left:5px solid #eee;padding-left:1em}.inheritance em{font-style:normal;font-weight:bold}.desc h2{font-weight:400;font-size:1.25em}.desc h3{font-size:1em}.desc dt code{background:inherit}.source summary,.git-link-div{color:#666;text-align:right;font-weight:400;font-size:.8em;text-transform:uppercase}.source summary > *{white-space:nowrap;cursor:pointer}.git-link{color:inherit;margin-left:1em}.source pre{max-height:500px;overflow:auto;margin:0}.source pre code{font-size:12px;overflow:visible}.hlist{list-style:none}.hlist li{display:inline}.hlist li:after{content:',\2002'}.hlist li:last-child:after{content:none}.hlist .hlist{display:inline;padding-left:1em}img{max-width:100%}td{padding:0 .5em}.admonition{padding:.1em .5em;margin-bottom:1em}.admonition-title{font-weight:bold}.admonition.note,.admonition.info,.admonition.important{background:#aef}.admonition.todo,.admonition.versionadded,.admonition.tip,.admonition.hint{background:#dfd}.admonition.warning,.admonition.versionchanged,.admonition.deprecated{background:#fd4}.admonition.error,.admonition.danger,.admonition.caution{background:lightpink}</style>
<style media="screen and (min-width: 700px)">@media screen and (min-width:700px){#sidebar{width:30%;height:100vh;overflow:auto;position:sticky;top:0}#content{width:70%;max-width:100ch;padding:3em 4em;border-left:1px solid #ddd}pre code{font-size:1em}.item .name{font-size:1em}main{display:flex;flex-direction:row-reverse;justify-content:flex-end}.toc ul ul,#index ul{padding-left:1.5em}.toc > ul > li{margin-top:.5em}}</style>
<style media="print">@media print{#sidebar h1{page-break-before:always}.source{display:none}}@media print{*{background:transparent !important;color:#000 !important;box-shadow:none !important;text-shadow:none !important}a[href]:after{content:" (" attr(href) ")";font-size:90%}a[href][title]:after{content:none}abbr[title]:after{content:" (" attr(title) ")"}.ir a:after,a[href^="javascript:"]:after,a[href^="#"]:after{content:""}pre,blockquote{border:1px solid #999;page-break-inside:avoid}thead{display:table-header-group}tr,img{page-break-inside:avoid}img{max-width:100% !important}@page{margin:0.5cm}p,h2,h3{orphans:3;widows:3}h1,h2,h3,h4,h5,h6{page-break-after:avoid}}</style>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js" integrity="sha256-Uv3H6lx7dJmRfRvH8TH6kJD1TSK1aFcwgx+mdg3epi8=" crossorigin></script>
<script>window.addEventListener('DOMContentLoaded', () => hljs.initHighlighting())</script>
</head>
<body>
<main>
<article id="content">
<header>
<h1 class="title">Module <code>raffiot.result</code></h1>
</header>
<section id="section-intro">
<p>Data structure to represent the result of computation.</p>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">&#34;&#34;&#34;
Data structure to represent the result of computation.
&#34;&#34;&#34;

from __future__ import annotations
from typing import TypeVar, Generic, Callable, Any
from typing_extensions import final
from dataclasses import dataclass
from raffiot import _MatchError

E = TypeVar(&#34;E&#34;)
A = TypeVar(&#34;A&#34;)
E2 = TypeVar(&#34;E2&#34;)
A2 = TypeVar(&#34;A2&#34;)
X = TypeVar(&#34;X&#34;)


def safe(f: Callable[..., Result[E, A]]) -&gt; Callable[..., Result[E, A]]:
    &#34;&#34;&#34;
    Simple decorator to ensure all exception are caught and transformed into
    panics.

    A function that returns a Result[E,A] should never raise an exception but
    instead return a panic. This decorator make sure of it.

    :param f:
    :return:
    &#34;&#34;&#34;

    def wrapper(*args: Any, **kwargs: Any) -&gt; Any:
        try:
            return f(*args, **kwargs)
        except Exception as exception:
            return Panic(exception)

    return wrapper


class Result(Generic[E, A]):
    &#34;&#34;&#34;
    The Result[E,A] data structure represents the result of a computation. It has
    3 possible cases:

    - Ok(some_value: A)
            The computation succeeded.
            The value some_value, of type A, is the result of the computation
    - Error(some_error: E)
            The computation failed with an expected error.
            The error some_error, of type E, is the expected error encountered.
    - Panic(some_exception: Exception)
            The computation failed on an unexpected error.
            The exception some_exception is the unexpected error encountered.

    The distinction between errors (expected failures) and panics (unexpected
    failures) is essential.

    Errors are failures your program is prepared to deal with safely. An error
    simply means some operation was not successful, but your program is still
    behaving nicely. Nothing terribly wrong happened. Generally errors belong to
    your business domain. You can take any type as E.

    Panics, on the contrary, are failures you never expected. Your computation
    can not progress further. All you can do when panics occur, is stopping your
    computation gracefully (like releasing resources before dying). The panic type
    is always Exception.

    As an example, if your program is an HTTP server. Errors are bad requests
    (error code 400) while panics are internal server errors (error code 500).
    Receiving bad request is part of the normal life of any HTTP server, it must
    know how to reply nicely. But internal server errors are bugs.
    &#34;&#34;&#34;

    @final
    def fold(
        self,
        on_success: Callable[[A], X],
        on_error: Callable[[E], X],
        on_panic: Callable[[Exception], X],
    ) -&gt; X:
        &#34;&#34;&#34;
        Transform this Result[E,A] into X.
        :param on_success: is called if this result is a Ok.
        :param on_error: is called if this result is a Error.
        :param on_panic: is called if this result is a Panic.
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return on_success(self.success)
        if isinstance(self, Error):
            return on_error(self.error)
        if isinstance(self, Panic):
            return on_panic(self.exception)
        raise _MatchError(f&#34;{self} should be a Result&#34;)

    @final
    def fold_raise(self, on_success: Callable[[A], X], on_error: Callable[[E], X]) -&gt; X:
        &#34;&#34;&#34;
        Transform this Result[E,A] into X if this result is an Ok or Error.
        But raise the stored exception is this is a panic.

        It is useful to raise an exception on panics.

        :param on_success: is called if this result is a Ok.
        :param on_error: is called if this result is a Error.
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return on_success(self.success)
        if isinstance(self, Error):
            return on_error(self.error)
        if isinstance(self, Panic):
            raise self.exception
        raise _MatchError(f&#34;{self} should be a Result&#34;)

    @final
    def flat_map(self, f: Callable[[A], Result[E, A2]]) -&gt; Result[E, A2]:
        &#34;&#34;&#34;
        The usual monadic operation called
            - bind, &gt;&gt;=: in Haskell
            - flatMap: in Scala
            - andThem: in Elm
            ...

        Chain operations returning results.

        :param f: operation to perform it this result is an Ok.
        :return: the result combined result.
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return safe(f)(self.success)
        return self

    @final
    def tri_map(
        self,
        f: Callable[[A], A2],
        g: Callable[[E], E2],
        h: Callable[[Exception], Exception],
    ) -&gt; Result[E2, A2]:
        &#34;&#34;&#34;
        Transform the value/error/exception stored in this result.
        :param f: how to transform the value a if this result is Ok(a)
        :param g: how to transform the error e if this result is Error(e)
        :param h: how to transform the exception p if this result is Panic(p)
        :return: the &#34;same&#34; result with the stored value transformed.
        &#34;&#34;&#34;
        return self.fold(
            safe(lambda x: Ok(f(x))),
            safe(lambda x: Error(g(x))),
            safe(lambda x: Panic(h(x))),
        )

    @final
    def is_ok(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Ok
        &#34;&#34;&#34;
        return isinstance(self, Ok)

    @final
    def is_error(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Error
        &#34;&#34;&#34;
        return isinstance(self, Error)

    @final
    def is_panic(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Panic
        &#34;&#34;&#34;
        return isinstance(self, Panic)

    @final
    def map(self, f: Callable[[A], A2]) -&gt; Result[E, A2]:
        &#34;&#34;&#34;
        Transform the value stored in Ok, it this result is an Ok.
        :param f: the transformation function.
        :return:
        &#34;&#34;&#34;
        return self.flat_map(lambda x: Ok(f(x)))

    @final
    def ap(self: Result[E, Callable[[X], A]], arg: Result[E, X]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        Noting functions from X to A: X -&gt; A.

        If this result represent a computation returning a function f: X -&gt; A
        and arg represent a computation returning a value x: X.
        self.ap(arg) represents the computation returning f(x): A
        &#34;&#34;&#34;
        return self.flat_map(lambda f: arg.map(f))

    @final
    def flatten(self: Result[E, Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        The concatenation function on results.
        &#34;&#34;&#34;
        return self.flat_map(lambda x: x)

    @final
    @safe
    def map_error(self, f: Callable[[E], E2]) -&gt; Result[E2, A]:
        &#34;&#34;&#34;
        Transform the error stored if this result is an Error
        :param f: the transformation function
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Error):
            return Error(f(self.error))
        return self  # type: ignore

    @final
    def catch(self, handler: Callable[[E], Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        React to errors (the except part of a try-except).

        If this result is an Error(some_error), then replace it with handler(some_error).
        Otherwise, do nothing.
        &#34;&#34;&#34;
        if isinstance(self, Error):
            return handler(self.error)
        return self

    @final
    def map_panic(self, f: Callable[[Exception], Exception]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        Transform the exception stored if this result is a Panic(some_exception).
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            return Panic(f(self.exception))
        return self

    @final
    def recover(self, handler: Callable[[Exception], Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        React to panics (the except part of a try-except).

        If this result is a Panic(exception), replace it by handler(exception).
        Otherwise do nothing.
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            return handler(self.exception)
        return self

    @final
    def raise_on_panic(self) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        If this result is an Ok or Error, do nothing.
        If it is a Panic(some_exception), raise the exception.

        Use with extreme care since it raise exception.
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            raise self.exception
        return self


@final
@dataclass
class Ok(Result[E, A]):
    &#34;&#34;&#34;
    The result of a successful computation.
    &#34;&#34;&#34;

    success: A


@final
@dataclass
class Error(Result[E, A]):
    &#34;&#34;&#34;
    The result of a computation that failed on an excepted normal error case.
    The program is still in a valid state and can progress safely.
    &#34;&#34;&#34;

    error: E


@final
@dataclass
class Panic(Result[E, A]):
    &#34;&#34;&#34;
    The result of a computation that failed unexpectedly.
    The program is not in a valid state and must terminate safely.
    &#34;&#34;&#34;

    exception: Exception


def pure(a: A) -&gt; Result[Any, A]:
    &#34;&#34;&#34;
    Alias for Ok(a).
    &#34;&#34;&#34;
    return Ok(a)


def error(error: E) -&gt; Result[E, Any]:
    &#34;&#34;&#34;
    Alias for Error(error).
    &#34;&#34;&#34;
    return Error(error)


def panic(exception: Exception) -&gt; Result[Any, Any]:
    &#34;&#34;&#34;
    Alias for Panic(exception).
    &#34;&#34;&#34;
    return Panic(exception)


def returns_result(f: Callable[..., Result[E, A]]) -&gt; Callable[..., Result[E, A]]:
    &#34;&#34;&#34;
    Decorator that transform a function f returning A,
    into a function f returning Result[E,A].

    All exceptions are transformed into panics.
    &#34;&#34;&#34;

    def wrapper(*args: Any, **kwargs: Any) -&gt; Any:
        try:
            return Ok(f(*args, **kwargs))
        except Exception as exception:
            return Panic(exception)

    return wrapper</code></pre>
</details>
</section>
<section>
</section>
<section>
</section>
<section>
<h2 class="section-title" id="header-functions">Functions</h2>
<dl>
<dt id="raffiot.result.error"><code class="name flex">
<span>def <span class="ident">error</span></span>(<span>error: E) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, typing.Any]</span>
</code></dt>
<dd>
<div class="desc"><p>Alias for Error(error).</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def error(error: E) -&gt; Result[E, Any]:
    &#34;&#34;&#34;
    Alias for Error(error).
    &#34;&#34;&#34;
    return Error(error)</code></pre>
</details>
</dd>
<dt id="raffiot.result.panic"><code class="name flex">
<span>def <span class="ident">panic</span></span>(<span>exception: Exception) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[typing.Any, typing.Any]</span>
</code></dt>
<dd>
<div class="desc"><p>Alias for Panic(exception).</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def panic(exception: Exception) -&gt; Result[Any, Any]:
    &#34;&#34;&#34;
    Alias for Panic(exception).
    &#34;&#34;&#34;
    return Panic(exception)</code></pre>
</details>
</dd>
<dt id="raffiot.result.pure"><code class="name flex">
<span>def <span class="ident">pure</span></span>(<span>a: A) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[typing.Any, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Alias for Ok(a).</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def pure(a: A) -&gt; Result[Any, A]:
    &#34;&#34;&#34;
    Alias for Ok(a).
    &#34;&#34;&#34;
    return Ok(a)</code></pre>
</details>
</dd>
<dt id="raffiot.result.returns_result"><code class="name flex">
<span>def <span class="ident">returns_result</span></span>(<span>f: Callable[..., <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A]]) ‑> Callable[..., <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]]</span>
</code></dt>
<dd>
<div class="desc"><p>Decorator that transform a function f returning A,
into a function f returning Result[E,A].</p>
<p>All exceptions are transformed into panics.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def returns_result(f: Callable[..., Result[E, A]]) -&gt; Callable[..., Result[E, A]]:
    &#34;&#34;&#34;
    Decorator that transform a function f returning A,
    into a function f returning Result[E,A].

    All exceptions are transformed into panics.
    &#34;&#34;&#34;

    def wrapper(*args: Any, **kwargs: Any) -&gt; Any:
        try:
            return Ok(f(*args, **kwargs))
        except Exception as exception:
            return Panic(exception)

    return wrapper</code></pre>
</details>
</dd>
<dt id="raffiot.result.safe"><code class="name flex">
<span>def <span class="ident">safe</span></span>(<span>f: Callable[..., <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A]]) ‑> Callable[..., <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]]</span>
</code></dt>
<dd>
<div class="desc"><p>Simple decorator to ensure all exception are caught and transformed into
panics.</p>
<p>A function that returns a Result[E,A] should never raise an exception but
instead return a panic. This decorator make sure of it.</p>
<p>:param f:
:return:</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def safe(f: Callable[..., Result[E, A]]) -&gt; Callable[..., Result[E, A]]:
    &#34;&#34;&#34;
    Simple decorator to ensure all exception are caught and transformed into
    panics.

    A function that returns a Result[E,A] should never raise an exception but
    instead return a panic. This decorator make sure of it.

    :param f:
    :return:
    &#34;&#34;&#34;

    def wrapper(*args: Any, **kwargs: Any) -&gt; Any:
        try:
            return f(*args, **kwargs)
        except Exception as exception:
            return Panic(exception)

    return wrapper</code></pre>
</details>
</dd>
</dl>
</section>
<section>
<h2 class="section-title" id="header-classes">Classes</h2>
<dl>
<dt id="raffiot.result.Error"><code class="flex name class">
<span>class <span class="ident">Error</span></span>
<span>(</span><span>error: E)</span>
</code></dt>
<dd>
<div class="desc"><p>The result of a computation that failed on an excepted normal error case.
The program is still in a valid state and can progress safely.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
@dataclass
class Error(Result[E, A]):
    &#34;&#34;&#34;
    The result of a computation that failed on an excepted normal error case.
    The program is still in a valid state and can progress safely.
    &#34;&#34;&#34;

    error: E</code></pre>
</details>
<h3>Ancestors</h3>
<ul class="hlist">
<li><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></li>
<li>typing.Generic</li>
</ul>
<h3>Class variables</h3>
<dl>
<dt id="raffiot.result.Error.error"><code class="name">var <span class="ident">error</span> : ~E</code></dt>
<dd>
<div class="desc"></div>
</dd>
</dl>
<h3>Inherited members</h3>
<ul class="hlist">
<li><code><b><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></b></code>:
<ul class="hlist">
<li><code><a title="raffiot.result.Result.ap" href="#raffiot.result.Result.ap">ap</a></code></li>
<li><code><a title="raffiot.result.Result.catch" href="#raffiot.result.Result.catch">catch</a></code></li>
<li><code><a title="raffiot.result.Result.flat_map" href="#raffiot.result.Result.flat_map">flat_map</a></code></li>
<li><code><a title="raffiot.result.Result.flatten" href="#raffiot.result.Result.flatten">flatten</a></code></li>
<li><code><a title="raffiot.result.Result.fold" href="#raffiot.result.Result.fold">fold</a></code></li>
<li><code><a title="raffiot.result.Result.fold_raise" href="#raffiot.result.Result.fold_raise">fold_raise</a></code></li>
<li><code><a title="raffiot.result.Result.is_error" href="#raffiot.result.Result.is_error">is_error</a></code></li>
<li><code><a title="raffiot.result.Result.is_ok" href="#raffiot.result.Result.is_ok">is_ok</a></code></li>
<li><code><a title="raffiot.result.Result.is_panic" href="#raffiot.result.Result.is_panic">is_panic</a></code></li>
<li><code><a title="raffiot.result.Result.map" href="#raffiot.result.Result.map">map</a></code></li>
<li><code><a title="raffiot.result.Result.map_panic" href="#raffiot.result.Result.map_panic">map_panic</a></code></li>
<li><code><a title="raffiot.result.Result.raise_on_panic" href="#raffiot.result.Result.raise_on_panic">raise_on_panic</a></code></li>
<li><code><a title="raffiot.result.Result.recover" href="#raffiot.result.Result.recover">recover</a></code></li>
<li><code><a title="raffiot.result.Result.tri_map" href="#raffiot.result.Result.tri_map">tri_map</a></code></li>
</ul>
</li>
</ul>
</dd>
<dt id="raffiot.result.Ok"><code class="flex name class">
<span>class <span class="ident">Ok</span></span>
<span>(</span><span>success: A)</span>
</code></dt>
<dd>
<div class="desc"><p>The result of a successful computation.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
@dataclass
class Ok(Result[E, A]):
    &#34;&#34;&#34;
    The result of a successful computation.
    &#34;&#34;&#34;

    success: A</code></pre>
</details>
<h3>Ancestors</h3>
<ul class="hlist">
<li><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></li>
<li>typing.Generic</li>
</ul>
<h3>Class variables</h3>
<dl>
<dt id="raffiot.result.Ok.success"><code class="name">var <span class="ident">success</span> : ~A</code></dt>
<dd>
<div class="desc"></div>
</dd>
</dl>
<h3>Inherited members</h3>
<ul class="hlist">
<li><code><b><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></b></code>:
<ul class="hlist">
<li><code><a title="raffiot.result.Result.ap" href="#raffiot.result.Result.ap">ap</a></code></li>
<li><code><a title="raffiot.result.Result.catch" href="#raffiot.result.Result.catch">catch</a></code></li>
<li><code><a title="raffiot.result.Result.flat_map" href="#raffiot.result.Result.flat_map">flat_map</a></code></li>
<li><code><a title="raffiot.result.Result.flatten" href="#raffiot.result.Result.flatten">flatten</a></code></li>
<li><code><a title="raffiot.result.Result.fold" href="#raffiot.result.Result.fold">fold</a></code></li>
<li><code><a title="raffiot.result.Result.fold_raise" href="#raffiot.result.Result.fold_raise">fold_raise</a></code></li>
<li><code><a title="raffiot.result.Result.is_error" href="#raffiot.result.Result.is_error">is_error</a></code></li>
<li><code><a title="raffiot.result.Result.is_ok" href="#raffiot.result.Result.is_ok">is_ok</a></code></li>
<li><code><a title="raffiot.result.Result.is_panic" href="#raffiot.result.Result.is_panic">is_panic</a></code></li>
<li><code><a title="raffiot.result.Result.map" href="#raffiot.result.Result.map">map</a></code></li>
<li><code><a title="raffiot.result.Result.map_panic" href="#raffiot.result.Result.map_panic">map_panic</a></code></li>
<li><code><a title="raffiot.result.Result.raise_on_panic" href="#raffiot.result.Result.raise_on_panic">raise_on_panic</a></code></li>
<li><code><a title="raffiot.result.Result.recover" href="#raffiot.result.Result.recover">recover</a></code></li>
<li><code><a title="raffiot.result.Result.tri_map" href="#raffiot.result.Result.tri_map">tri_map</a></code></li>
</ul>
</li>
</ul>
</dd>
<dt id="raffiot.result.Panic"><code class="flex name class">
<span>class <span class="ident">Panic</span></span>
<span>(</span><span>exception: Exception)</span>
</code></dt>
<dd>
<div class="desc"><p>The result of a computation that failed unexpectedly.
The program is not in a valid state and must terminate safely.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
@dataclass
class Panic(Result[E, A]):
    &#34;&#34;&#34;
    The result of a computation that failed unexpectedly.
    The program is not in a valid state and must terminate safely.
    &#34;&#34;&#34;

    exception: Exception</code></pre>
</details>
<h3>Ancestors</h3>
<ul class="hlist">
<li><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></li>
<li>typing.Generic</li>
</ul>
<h3>Class variables</h3>
<dl>
<dt id="raffiot.result.Panic.exception"><code class="name">var <span class="ident">exception</span> : Exception</code></dt>
<dd>
<div class="desc"></div>
</dd>
</dl>
<h3>Inherited members</h3>
<ul class="hlist">
<li><code><b><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></b></code>:
<ul class="hlist">
<li><code><a title="raffiot.result.Result.ap" href="#raffiot.result.Result.ap">ap</a></code></li>
<li><code><a title="raffiot.result.Result.catch" href="#raffiot.result.Result.catch">catch</a></code></li>
<li><code><a title="raffiot.result.Result.flat_map" href="#raffiot.result.Result.flat_map">flat_map</a></code></li>
<li><code><a title="raffiot.result.Result.flatten" href="#raffiot.result.Result.flatten">flatten</a></code></li>
<li><code><a title="raffiot.result.Result.fold" href="#raffiot.result.Result.fold">fold</a></code></li>
<li><code><a title="raffiot.result.Result.fold_raise" href="#raffiot.result.Result.fold_raise">fold_raise</a></code></li>
<li><code><a title="raffiot.result.Result.is_error" href="#raffiot.result.Result.is_error">is_error</a></code></li>
<li><code><a title="raffiot.result.Result.is_ok" href="#raffiot.result.Result.is_ok">is_ok</a></code></li>
<li><code><a title="raffiot.result.Result.is_panic" href="#raffiot.result.Result.is_panic">is_panic</a></code></li>
<li><code><a title="raffiot.result.Result.map" href="#raffiot.result.Result.map">map</a></code></li>
<li><code><a title="raffiot.result.Result.map_panic" href="#raffiot.result.Result.map_panic">map_panic</a></code></li>
<li><code><a title="raffiot.result.Result.raise_on_panic" href="#raffiot.result.Result.raise_on_panic">raise_on_panic</a></code></li>
<li><code><a title="raffiot.result.Result.recover" href="#raffiot.result.Result.recover">recover</a></code></li>
<li><code><a title="raffiot.result.Result.tri_map" href="#raffiot.result.Result.tri_map">tri_map</a></code></li>
</ul>
</li>
</ul>
</dd>
<dt id="raffiot.result.Result"><code class="flex name class">
<span>class <span class="ident">Result</span></span>
</code></dt>
<dd>
<div class="desc"><p>The Result[E,A] data structure represents the result of a computation. It has
3 possible cases:</p>
<ul>
<li>Ok(some_value: A)
The computation succeeded.
The value some_value, of type A, is the result of the computation</li>
<li>Error(some_error: E)
The computation failed with an expected error.
The error some_error, of type E, is the expected error encountered.</li>
<li>Panic(some_exception: Exception)
The computation failed on an unexpected error.
The exception some_exception is the unexpected error encountered.</li>
</ul>
<p>The distinction between errors (expected failures) and panics (unexpected
failures) is essential.</p>
<p>Errors are failures your program is prepared to deal with safely. An error
simply means some operation was not successful, but your program is still
behaving nicely. Nothing terribly wrong happened. Generally errors belong to
your business domain. You can take any type as E.</p>
<p>Panics, on the contrary, are failures you never expected. Your computation
can not progress further. All you can do when panics occur, is stopping your
computation gracefully (like releasing resources before dying). The panic type
is always Exception.</p>
<p>As an example, if your program is an HTTP server. Errors are bad requests
(error code 400) while panics are internal server errors (error code 500).
Receiving bad request is part of the normal life of any HTTP server, it must
know how to reply nicely. But internal server errors are bugs.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">class Result(Generic[E, A]):
    &#34;&#34;&#34;
    The Result[E,A] data structure represents the result of a computation. It has
    3 possible cases:

    - Ok(some_value: A)
            The computation succeeded.
            The value some_value, of type A, is the result of the computation
    - Error(some_error: E)
            The computation failed with an expected error.
            The error some_error, of type E, is the expected error encountered.
    - Panic(some_exception: Exception)
            The computation failed on an unexpected error.
            The exception some_exception is the unexpected error encountered.

    The distinction between errors (expected failures) and panics (unexpected
    failures) is essential.

    Errors are failures your program is prepared to deal with safely. An error
    simply means some operation was not successful, but your program is still
    behaving nicely. Nothing terribly wrong happened. Generally errors belong to
    your business domain. You can take any type as E.

    Panics, on the contrary, are failures you never expected. Your computation
    can not progress further. All you can do when panics occur, is stopping your
    computation gracefully (like releasing resources before dying). The panic type
    is always Exception.

    As an example, if your program is an HTTP server. Errors are bad requests
    (error code 400) while panics are internal server errors (error code 500).
    Receiving bad request is part of the normal life of any HTTP server, it must
    know how to reply nicely. But internal server errors are bugs.
    &#34;&#34;&#34;

    @final
    def fold(
        self,
        on_success: Callable[[A], X],
        on_error: Callable[[E], X],
        on_panic: Callable[[Exception], X],
    ) -&gt; X:
        &#34;&#34;&#34;
        Transform this Result[E,A] into X.
        :param on_success: is called if this result is a Ok.
        :param on_error: is called if this result is a Error.
        :param on_panic: is called if this result is a Panic.
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return on_success(self.success)
        if isinstance(self, Error):
            return on_error(self.error)
        if isinstance(self, Panic):
            return on_panic(self.exception)
        raise _MatchError(f&#34;{self} should be a Result&#34;)

    @final
    def fold_raise(self, on_success: Callable[[A], X], on_error: Callable[[E], X]) -&gt; X:
        &#34;&#34;&#34;
        Transform this Result[E,A] into X if this result is an Ok or Error.
        But raise the stored exception is this is a panic.

        It is useful to raise an exception on panics.

        :param on_success: is called if this result is a Ok.
        :param on_error: is called if this result is a Error.
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return on_success(self.success)
        if isinstance(self, Error):
            return on_error(self.error)
        if isinstance(self, Panic):
            raise self.exception
        raise _MatchError(f&#34;{self} should be a Result&#34;)

    @final
    def flat_map(self, f: Callable[[A], Result[E, A2]]) -&gt; Result[E, A2]:
        &#34;&#34;&#34;
        The usual monadic operation called
            - bind, &gt;&gt;=: in Haskell
            - flatMap: in Scala
            - andThem: in Elm
            ...

        Chain operations returning results.

        :param f: operation to perform it this result is an Ok.
        :return: the result combined result.
        &#34;&#34;&#34;
        if isinstance(self, Ok):
            return safe(f)(self.success)
        return self

    @final
    def tri_map(
        self,
        f: Callable[[A], A2],
        g: Callable[[E], E2],
        h: Callable[[Exception], Exception],
    ) -&gt; Result[E2, A2]:
        &#34;&#34;&#34;
        Transform the value/error/exception stored in this result.
        :param f: how to transform the value a if this result is Ok(a)
        :param g: how to transform the error e if this result is Error(e)
        :param h: how to transform the exception p if this result is Panic(p)
        :return: the &#34;same&#34; result with the stored value transformed.
        &#34;&#34;&#34;
        return self.fold(
            safe(lambda x: Ok(f(x))),
            safe(lambda x: Error(g(x))),
            safe(lambda x: Panic(h(x))),
        )

    @final
    def is_ok(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Ok
        &#34;&#34;&#34;
        return isinstance(self, Ok)

    @final
    def is_error(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Error
        &#34;&#34;&#34;
        return isinstance(self, Error)

    @final
    def is_panic(self) -&gt; bool:
        &#34;&#34;&#34;
        :return: True if this result is an Panic
        &#34;&#34;&#34;
        return isinstance(self, Panic)

    @final
    def map(self, f: Callable[[A], A2]) -&gt; Result[E, A2]:
        &#34;&#34;&#34;
        Transform the value stored in Ok, it this result is an Ok.
        :param f: the transformation function.
        :return:
        &#34;&#34;&#34;
        return self.flat_map(lambda x: Ok(f(x)))

    @final
    def ap(self: Result[E, Callable[[X], A]], arg: Result[E, X]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        Noting functions from X to A: X -&gt; A.

        If this result represent a computation returning a function f: X -&gt; A
        and arg represent a computation returning a value x: X.
        self.ap(arg) represents the computation returning f(x): A
        &#34;&#34;&#34;
        return self.flat_map(lambda f: arg.map(f))

    @final
    def flatten(self: Result[E, Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        The concatenation function on results.
        &#34;&#34;&#34;
        return self.flat_map(lambda x: x)

    @final
    @safe
    def map_error(self, f: Callable[[E], E2]) -&gt; Result[E2, A]:
        &#34;&#34;&#34;
        Transform the error stored if this result is an Error
        :param f: the transformation function
        :return:
        &#34;&#34;&#34;
        if isinstance(self, Error):
            return Error(f(self.error))
        return self  # type: ignore

    @final
    def catch(self, handler: Callable[[E], Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        React to errors (the except part of a try-except).

        If this result is an Error(some_error), then replace it with handler(some_error).
        Otherwise, do nothing.
        &#34;&#34;&#34;
        if isinstance(self, Error):
            return handler(self.error)
        return self

    @final
    def map_panic(self, f: Callable[[Exception], Exception]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        Transform the exception stored if this result is a Panic(some_exception).
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            return Panic(f(self.exception))
        return self

    @final
    def recover(self, handler: Callable[[Exception], Result[E, A]]) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        React to panics (the except part of a try-except).

        If this result is a Panic(exception), replace it by handler(exception).
        Otherwise do nothing.
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            return handler(self.exception)
        return self

    @final
    def raise_on_panic(self) -&gt; Result[E, A]:
        &#34;&#34;&#34;
        If this result is an Ok or Error, do nothing.
        If it is a Panic(some_exception), raise the exception.

        Use with extreme care since it raise exception.
        &#34;&#34;&#34;
        if isinstance(self, Panic):
            raise self.exception
        return self</code></pre>
</details>
<h3>Ancestors</h3>
<ul class="hlist">
<li>typing.Generic</li>
</ul>
<h3>Subclasses</h3>
<ul class="hlist">
<li><a title="raffiot.result.Error" href="#raffiot.result.Error">Error</a></li>
<li><a title="raffiot.result.Ok" href="#raffiot.result.Ok">Ok</a></li>
<li><a title="raffiot.result.Panic" href="#raffiot.result.Panic">Panic</a></li>
</ul>
<h3>Methods</h3>
<dl>
<dt id="raffiot.result.Result.ap"><code class="name flex">
<span>def <span class="ident">ap</span></span>(<span>self: <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, Callable[[X], A]], arg: <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, X]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Noting functions from X to A: X -&gt; A.</p>
<p>If this result represent a computation returning a function f: X -&gt; A
and arg represent a computation returning a value x: X.
self.ap(arg) represents the computation returning f(x): A</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def ap(self: Result[E, Callable[[X], A]], arg: Result[E, X]) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    Noting functions from X to A: X -&gt; A.

    If this result represent a computation returning a function f: X -&gt; A
    and arg represent a computation returning a value x: X.
    self.ap(arg) represents the computation returning f(x): A
    &#34;&#34;&#34;
    return self.flat_map(lambda f: arg.map(f))</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.catch"><code class="name flex">
<span>def <span class="ident">catch</span></span>(<span>self, handler: Callable[[E], <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A]]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>React to errors (the except part of a try-except).</p>
<p>If this result is an Error(some_error), then replace it with handler(some_error).
Otherwise, do nothing.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def catch(self, handler: Callable[[E], Result[E, A]]) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    React to errors (the except part of a try-except).

    If this result is an Error(some_error), then replace it with handler(some_error).
    Otherwise, do nothing.
    &#34;&#34;&#34;
    if isinstance(self, Error):
        return handler(self.error)
    return self</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.flat_map"><code class="name flex">
<span>def <span class="ident">flat_map</span></span>(<span>self, f: Callable[[A], <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A2]]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>The usual monadic operation called
- bind, &gt;&gt;=: in Haskell
- flatMap: in Scala
- andThem: in Elm
&hellip;</p>
<p>Chain operations returning results.</p>
<p>:param f: operation to perform it this result is an Ok.
:return: the result combined result.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def flat_map(self, f: Callable[[A], Result[E, A2]]) -&gt; Result[E, A2]:
    &#34;&#34;&#34;
    The usual monadic operation called
        - bind, &gt;&gt;=: in Haskell
        - flatMap: in Scala
        - andThem: in Elm
        ...

    Chain operations returning results.

    :param f: operation to perform it this result is an Ok.
    :return: the result combined result.
    &#34;&#34;&#34;
    if isinstance(self, Ok):
        return safe(f)(self.success)
    return self</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.flatten"><code class="name flex">
<span>def <span class="ident">flatten</span></span>(<span>self: <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A]]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>The concatenation function on results.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def flatten(self: Result[E, Result[E, A]]) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    The concatenation function on results.
    &#34;&#34;&#34;
    return self.flat_map(lambda x: x)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.fold"><code class="name flex">
<span>def <span class="ident">fold</span></span>(<span>self, on_success: Callable[[A], X], on_error: Callable[[E], X], on_panic: Callable[[Exception], X]) ‑> ~X</span>
</code></dt>
<dd>
<div class="desc"><p>Transform this Result[E,A] into X.
:param on_success: is called if this result is a Ok.
:param on_error: is called if this result is a Error.
:param on_panic: is called if this result is a Panic.
:return:</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def fold(
    self,
    on_success: Callable[[A], X],
    on_error: Callable[[E], X],
    on_panic: Callable[[Exception], X],
) -&gt; X:
    &#34;&#34;&#34;
    Transform this Result[E,A] into X.
    :param on_success: is called if this result is a Ok.
    :param on_error: is called if this result is a Error.
    :param on_panic: is called if this result is a Panic.
    :return:
    &#34;&#34;&#34;
    if isinstance(self, Ok):
        return on_success(self.success)
    if isinstance(self, Error):
        return on_error(self.error)
    if isinstance(self, Panic):
        return on_panic(self.exception)
    raise _MatchError(f&#34;{self} should be a Result&#34;)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.fold_raise"><code class="name flex">
<span>def <span class="ident">fold_raise</span></span>(<span>self, on_success: Callable[[A], X], on_error: Callable[[E], X]) ‑> ~X</span>
</code></dt>
<dd>
<div class="desc"><p>Transform this Result[E,A] into X if this result is an Ok or Error.
But raise the stored exception is this is a panic.</p>
<p>It is useful to raise an exception on panics.</p>
<p>:param on_success: is called if this result is a Ok.
:param on_error: is called if this result is a Error.
:return:</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def fold_raise(self, on_success: Callable[[A], X], on_error: Callable[[E], X]) -&gt; X:
    &#34;&#34;&#34;
    Transform this Result[E,A] into X if this result is an Ok or Error.
    But raise the stored exception is this is a panic.

    It is useful to raise an exception on panics.

    :param on_success: is called if this result is a Ok.
    :param on_error: is called if this result is a Error.
    :return:
    &#34;&#34;&#34;
    if isinstance(self, Ok):
        return on_success(self.success)
    if isinstance(self, Error):
        return on_error(self.error)
    if isinstance(self, Panic):
        raise self.exception
    raise _MatchError(f&#34;{self} should be a Result&#34;)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.is_error"><code class="name flex">
<span>def <span class="ident">is_error</span></span>(<span>self) ‑> bool</span>
</code></dt>
<dd>
<div class="desc"><p>:return: True if this result is an Error</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def is_error(self) -&gt; bool:
    &#34;&#34;&#34;
    :return: True if this result is an Error
    &#34;&#34;&#34;
    return isinstance(self, Error)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.is_ok"><code class="name flex">
<span>def <span class="ident">is_ok</span></span>(<span>self) ‑> bool</span>
</code></dt>
<dd>
<div class="desc"><p>:return: True if this result is an Ok</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def is_ok(self) -&gt; bool:
    &#34;&#34;&#34;
    :return: True if this result is an Ok
    &#34;&#34;&#34;
    return isinstance(self, Ok)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.is_panic"><code class="name flex">
<span>def <span class="ident">is_panic</span></span>(<span>self) ‑> bool</span>
</code></dt>
<dd>
<div class="desc"><p>:return: True if this result is an Panic</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def is_panic(self) -&gt; bool:
    &#34;&#34;&#34;
    :return: True if this result is an Panic
    &#34;&#34;&#34;
    return isinstance(self, Panic)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.map"><code class="name flex">
<span>def <span class="ident">map</span></span>(<span>self, f: Callable[[A], A2]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the value stored in Ok, it this result is an Ok.
:param f: the transformation function.
:return:</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def map(self, f: Callable[[A], A2]) -&gt; Result[E, A2]:
    &#34;&#34;&#34;
    Transform the value stored in Ok, it this result is an Ok.
    :param f: the transformation function.
    :return:
    &#34;&#34;&#34;
    return self.flat_map(lambda x: Ok(f(x)))</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.map_error"><code class="name flex">
<span>def <span class="ident">map_error</span></span>(<span>*args: Any, **kwargs: Any) ‑> Any</span>
</code></dt>
<dd>
<div class="desc"></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def wrapper(*args: Any, **kwargs: Any) -&gt; Any:
    try:
        return f(*args, **kwargs)
    except Exception as exception:
        return Panic(exception)</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.map_panic"><code class="name flex">
<span>def <span class="ident">map_panic</span></span>(<span>self, f: Callable[[Exception], Exception]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the exception stored if this result is a Panic(some_exception).</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def map_panic(self, f: Callable[[Exception], Exception]) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    Transform the exception stored if this result is a Panic(some_exception).
    &#34;&#34;&#34;
    if isinstance(self, Panic):
        return Panic(f(self.exception))
    return self</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.raise_on_panic"><code class="name flex">
<span>def <span class="ident">raise_on_panic</span></span>(<span>self) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>If this result is an Ok or Error, do nothing.
If it is a Panic(some_exception), raise the exception.</p>
<p>Use with extreme care since it raise exception.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def raise_on_panic(self) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    If this result is an Ok or Error, do nothing.
    If it is a Panic(some_exception), raise the exception.

    Use with extreme care since it raise exception.
    &#34;&#34;&#34;
    if isinstance(self, Panic):
        raise self.exception
    return self</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.recover"><code class="name flex">
<span>def <span class="ident">recover</span></span>(<span>self, handler: Callable[[Exception], <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[E, A]]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E, ~A]</span>
</code></dt>
<dd>
<div class="desc"><p>React to panics (the except part of a try-except).</p>
<p>If this result is a Panic(exception), replace it by handler(exception).
Otherwise do nothing.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def recover(self, handler: Callable[[Exception], Result[E, A]]) -&gt; Result[E, A]:
    &#34;&#34;&#34;
    React to panics (the except part of a try-except).

    If this result is a Panic(exception), replace it by handler(exception).
    Otherwise do nothing.
    &#34;&#34;&#34;
    if isinstance(self, Panic):
        return handler(self.exception)
    return self</code></pre>
</details>
</dd>
<dt id="raffiot.result.Result.tri_map"><code class="name flex">
<span>def <span class="ident">tri_map</span></span>(<span>self, f: Callable[[A], A2], g: Callable[[E], E2], h: Callable[[Exception], Exception]) ‑> <a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a>[~E2, ~A2]</span>
</code></dt>
<dd>
<div class="desc"><p>Transform the value/error/exception stored in this result.
:param f: how to transform the value a if this result is Ok(a)
:param g: how to transform the error e if this result is Error(e)
:param h: how to transform the exception p if this result is Panic(p)
:return: the "same" result with the stored value transformed.</p></div>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@final
def tri_map(
    self,
    f: Callable[[A], A2],
    g: Callable[[E], E2],
    h: Callable[[Exception], Exception],
) -&gt; Result[E2, A2]:
    &#34;&#34;&#34;
    Transform the value/error/exception stored in this result.
    :param f: how to transform the value a if this result is Ok(a)
    :param g: how to transform the error e if this result is Error(e)
    :param h: how to transform the exception p if this result is Panic(p)
    :return: the &#34;same&#34; result with the stored value transformed.
    &#34;&#34;&#34;
    return self.fold(
        safe(lambda x: Ok(f(x))),
        safe(lambda x: Error(g(x))),
        safe(lambda x: Panic(h(x))),
    )</code></pre>
</details>
</dd>
</dl>
</dd>
</dl>
</section>
</article>
<nav id="sidebar">
<h1>Index</h1>
<div class="toc">
<ul></ul>
</div>
<ul id="index">
<li><h3>Super-module</h3>
<ul>
<li><code><a title="raffiot" href="index.html">raffiot</a></code></li>
</ul>
</li>
<li><h3><a href="#header-functions">Functions</a></h3>
<ul class="">
<li><code><a title="raffiot.result.error" href="#raffiot.result.error">error</a></code></li>
<li><code><a title="raffiot.result.panic" href="#raffiot.result.panic">panic</a></code></li>
<li><code><a title="raffiot.result.pure" href="#raffiot.result.pure">pure</a></code></li>
<li><code><a title="raffiot.result.returns_result" href="#raffiot.result.returns_result">returns_result</a></code></li>
<li><code><a title="raffiot.result.safe" href="#raffiot.result.safe">safe</a></code></li>
</ul>
</li>
<li><h3><a href="#header-classes">Classes</a></h3>
<ul>
<li>
<h4><code><a title="raffiot.result.Error" href="#raffiot.result.Error">Error</a></code></h4>
<ul class="">
<li><code><a title="raffiot.result.Error.error" href="#raffiot.result.Error.error">error</a></code></li>
</ul>
</li>
<li>
<h4><code><a title="raffiot.result.Ok" href="#raffiot.result.Ok">Ok</a></code></h4>
<ul class="">
<li><code><a title="raffiot.result.Ok.success" href="#raffiot.result.Ok.success">success</a></code></li>
</ul>
</li>
<li>
<h4><code><a title="raffiot.result.Panic" href="#raffiot.result.Panic">Panic</a></code></h4>
<ul class="">
<li><code><a title="raffiot.result.Panic.exception" href="#raffiot.result.Panic.exception">exception</a></code></li>
</ul>
</li>
<li>
<h4><code><a title="raffiot.result.Result" href="#raffiot.result.Result">Result</a></code></h4>
<ul class="two-column">
<li><code><a title="raffiot.result.Result.ap" href="#raffiot.result.Result.ap">ap</a></code></li>
<li><code><a title="raffiot.result.Result.catch" href="#raffiot.result.Result.catch">catch</a></code></li>
<li><code><a title="raffiot.result.Result.flat_map" href="#raffiot.result.Result.flat_map">flat_map</a></code></li>
<li><code><a title="raffiot.result.Result.flatten" href="#raffiot.result.Result.flatten">flatten</a></code></li>
<li><code><a title="raffiot.result.Result.fold" href="#raffiot.result.Result.fold">fold</a></code></li>
<li><code><a title="raffiot.result.Result.fold_raise" href="#raffiot.result.Result.fold_raise">fold_raise</a></code></li>
<li><code><a title="raffiot.result.Result.is_error" href="#raffiot.result.Result.is_error">is_error</a></code></li>
<li><code><a title="raffiot.result.Result.is_ok" href="#raffiot.result.Result.is_ok">is_ok</a></code></li>
<li><code><a title="raffiot.result.Result.is_panic" href="#raffiot.result.Result.is_panic">is_panic</a></code></li>
<li><code><a title="raffiot.result.Result.map" href="#raffiot.result.Result.map">map</a></code></li>
<li><code><a title="raffiot.result.Result.map_error" href="#raffiot.result.Result.map_error">map_error</a></code></li>
<li><code><a title="raffiot.result.Result.map_panic" href="#raffiot.result.Result.map_panic">map_panic</a></code></li>
<li><code><a title="raffiot.result.Result.raise_on_panic" href="#raffiot.result.Result.raise_on_panic">raise_on_panic</a></code></li>
<li><code><a title="raffiot.result.Result.recover" href="#raffiot.result.Result.recover">recover</a></code></li>
<li><code><a title="raffiot.result.Result.tri_map" href="#raffiot.result.Result.tri_map">tri_map</a></code></li>
</ul>
</li>
</ul>
</li>
</ul>
</nav>
</main>
<footer id="footer">
<p>Generated by <a href="https://pdoc3.github.io/pdoc"><cite>pdoc</cite> 0.9.2</a>.</p>
</footer>
</body>
</html>